exports.run = (client, message, args) => {

	let gUser = message.guild.member(message.mentions.users.first()) || message.guild.members.get(args[0])
	if(!gUser) return message.reply("who?")
    let replies = ["That person is 0% gay!", "That person is 1% gay!", "That person is 2% gay!", "That person is 3% gay!", "That person is 4% gay!", "That person is 5% gay!", "That person is 6% gay!", "That person is 7% gay!", "That person is 8% gay!", "That person is 9% gay!", "That person is 10% gay!", "That person is 11% gay!", "That person is 12% gay!", "That person is 13% gay!", "That person is 14% gay!", "That person is 15% gay!", "That person is 16% gay!", "That person is 17% gay!", "That person is 18% gay!", "That person is 19% gay!", "That person is 20% gay!", "That person is 21% gay!", "That person is 22% gay!", "That person is 23% gay!", "That person is 24% gay!", "That person is 25% gay!", "That person is 26% gay!", "That person is 27% gay!", "That person is 28% gay!", "That person is 29% gay!", "That person is 30% gay!", "That person is 31% gay!", "That person is 32% gay!", "That person is 33% gay!", "That person is 34% gay!", "That person is 35% gay!", "That person is 36% gay!", "That person is 37% gay!", "That person is 38% gay!", "That person is 39% gay!", "That person is 40% gay!", "That person is 41% gay!", "That person is 42% gay!", "That person is 43% gay!", "That person is 44% gay!", "That person is 45% gay!", "That person is 46% gay!", "That person is 47% gay!", "That person is 48% gay!", "That person is 49% gay!", "That person is 50% gay!", "That person is 51% gay!", "That person is 52% gay!", "That person is 53% gay!", "That person is 54% gay!", "That person is 55% gay!", "That person is 56% gay!", "That person is 57% gay!", "That person is 58% gay!", "That person is 59% gay!", "That person is 60% gay!", "That person is 61% gay!", "That person is 62% gay!", "That person is 63% gay!", "That person is 64% gay!", "That person is 65% gay!", "That person is 66% gay!", "That person is 67% gay!", "That person is 68% gay!", "That person is 69% gay!", "That person is 70% gay!", "That person is 71% gay!", "That person is 72% gay!", "That person is 73% gay!", "That person is 74% gay!", "That person is 75% gay!", "That person is 76% gay!", "That person is 77% gay!", "That person is 78% gay!", "That person is 79% gay!", "That person is 80% gay!", "That person is 81% gay!", "That person is 82% gay!", "That person is 83% gay!", "That person is 84% gay!", "That person is 85% gay!", "That person is 86% gay!", "That person is 87% gay!", "That person is 88% gay!", "That person is 89% gay!", "That person is 90% gay!", "That person is 91% gay!", "That person is 92% gay!", "That person is 93% gay!", "That person is 94% gay!", "That person is 95% gay!", "That person is 96% gay!", "That person is 97% gay!", "That person is 98% gay!", "That person is 99% gay!", "That person is 100% gay!"];

    let answer = Math.floor((Math.random() * replies.length));
    let question = args.slice(1).join(" ");

    message.channel.send(`${replies[answer]}`);

};